remote_theme: "mmistakes/minimal-mistakes@4.15.2"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache
  
# Ook leuk:

# http://mattvh.github.io/solar-theme-jekyll/
# http://themes.jekyllrc.org/darcli/
# https://webjeda.com/hagura/
