remote_theme: mattvh/solar-theme-jekyll

# Ook leuk:
# http://pavelmakhov.com/jekyll-clean-dark/
# http://mattvh.github.io/solar-theme-jekyll/
# http://themes.jekyllrc.org/darcli/
# https://webjeda.com/hagura/
